

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: IOT
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Veljko22!!! 
    ports:
      - "5433:5432"
    networks:
      - iotdva

  mosquitto:
    container_name: mosquitto_container
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - iotdva
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  manager:
    image: emqx/ekuiper-manager:1.8.0
    container_name: manager
    ports:
      - "9082:9082"
    environment:
      DEFAULT_EKUIPER_ENDPOINT: "http://ekuiper:9081"
    networks:
      - iotdva

  ekuiper:
    image: lfedge/ekuiper:1.8.0
    ports:
      - "9081:9081"
    container_name: ekuiper
    hostname: ekuiper
    volumes:
      - ./eKuiper/data/init.json:/kuiper/data/init.json:ro
    environment:
      MQTT_SOURCE__DEFAULT__SERVER: "tcp://mosquitto_container:1883"
    networks:
      - iotdva

  analytics:
    container_name: analytics_container
    build:
      context: Analytics
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    networks:
      - iotdva
    depends_on:
      - manager
      - mosquitto
      - ekuiper

  sensor:
    container_name: sensor_container
    build:
      context: Sensor
      dockerfile: Dockerfile
    ports:
      - "6060:6060"
    networks:
      - iotdva
    depends_on:
      - postgres
      - mosquitto
    volumes:
      - ./AirQuality.csv:/sensor/config/AirQuality.csv

  springbootapp:
    container_name: event_info_container
    build:
      context: C:/Users/veljk/OneDrive/Desktop/Cetvrta godina/IOT2/RestApi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mosquitto
      - ekuiper
    networks:
      - iotdva

networks:
  iotdva:
    name: iotdva
